(define (abs x) (if (< x 0) -x x))
(define (square x) (* x x))
(define (average x y) (/ (+ x y) 2))
(define (sqrt x)
    (define (good-enouge? guess)
        (< (abs (- (square guess) x)) 0.001))
    (define (improve guess)
        ())
)
